version: "3.3"
services:
    client-panel:
        container_name: ycms-client-panel
        depends_on: 
            - redis
            - postgres
        build:
            context: docker/.
            dockerfile: Dockerfile
        volumes:
            - ../ycms-client-panel:/var/www/ycms/ycms-client-panel
            - ../ycms-docker:/var/www/ycms/ycms-docker
            - ../ycms-apps:/var/www/ycms/ycms-apps
            # - /etc/apache2/:/etc/apache2/
        network_mode: host
        restart: always

    redis:
        container_name: ycms-redis
        image: redis:5.0.9-alpine
        restart: always
        network_mode: host

    postgres:
        container_name: ycms-postgres
        build: 
            context: ./docker
            dockerfile: postgres.Dockerfile
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ycms_client
            PGDATA: './pgdata/'
        # volumes:
        #     - ./postgres-data/:/var/lib/postgresql/data # TODO
        restart: always
        network_mode: host

    # supervisor: # TODO
    #     container_name: ycms-supervisor
    #     build:
    #         context: .
    #         dockerfile: supervisor.Dockerfile
    #     volumes: 
    #         - ../ycms-docker:/var/www/ycms/ycms-docker
    #     network_mode: host

